name: Build and Push Docker Image

on:
  release:
    types: [created]
    tags:
      - "v*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Docker # This workflow is provisioning docker pre-installed
        run: |
          docker --version
          sudo apt-get update

      - name: Run Ansible Playbook
        run: "ansible-playbook ansible/playbook.yml \
            -e image_tag=${{ github.ref_name }} \
            -e project_name=${{ github.repository.name }} \
            -i localhost, -c local"
        continue-on-error: false # Stop the workflow on Ansible playbook failures